### ISSUE TITLE
Repeating - Run(session)

### ISSUE THREAD

**Issue by ekanna** [christopherhesse/rethinkgo#10]
Hi @christopherhesse ,

Just wondering, why we have to give every time Run(session)?

``` go
session, _ := r.Connect("localhost:28015", "test")
err := r.TableCreate("characters").Run(session).Exec()
rows := r.Table("characters").Run(session)
```

Can't you further simplify this for users? some thing like below.

``` go
db, _ := r.Connect("localhost:28015", "test")
err := db.TableCreate("characters")
rows := db.Table("characters")
```

Thanks

**Comment by elithrar** [comment]
@ekanna How would you differentiate between a statement you want to run and one you don't? There are cases where you might want to write only part of a query (and prepend it to a second part based on input). 

Note that `Run(session)` is also how the RethinkDB docs structure queries.

**Comment by ekanna** [comment]
@elithrar I was used to this http://howtonode.org/node-js-and-mongodb-getting-started-with-mongojs
and it is nice and simple. Just thought, why can't we implement some thing like that here?

**Comment by christopherhesse** [comment]
I considered doing this, but I would rather rethinkgo follow the official RethinkDB drivers as closely as possible.  One possible reason they might do it this way is that if queries are made off of sessions, then you could have two sessions used in the same query.  Also you might need to pass a session around to construct a query unless that case is handled too.

r.Table("characters") can't create a table, because that is used inside queries.  r.TableCreate("characters") probably could, but the driver would have to have more knowledge and the different commands would be less consistent.

If the official drivers change, I will change rethinkgo to follow those.  In the meantime, you could certainly make a wrapper around rethinkgo that does what you want.

rethinkgo is meant to be a minimal, rethinkdb-style driver.  There is certainly room for a driver with more features, and http://labix.org/mgo is a good example of such a driver, except it's for mongo instead of rethinkdb.

**Comment by ekanna** [comment]
@christopherhesse thanks for your explanation.
